RUN pip install --upgrade pip

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project to the container
COPY . .

# Set the Kedro project directory
ENV KEDRO_ENV=production
ENV KEDRO_PROJECT_PATH=/app/mylastml-schoolproject

# Set the entrypoint command to run Kedro
ENTRYPOINT ["kedro"]

# Set the default command arguments for Kedro
CMD ["run"]